project:
  type: book

book:
  title: "Социално - икономическа и епидемимиологична характертиска на редките тумори."
  author: "Костадин Костадинов"
  date: "12.08.2022 г."
- part: intro.qmd
- part: review.qmd
    chapters: 
      - basics.qmd
      - packages.qmd
  - part: aims.qmd
  - part: materials.qmd
  - part: results.qmd
  - part: discussions.qmd
  - part: conclusions.qmd
  -part: references.qmd
bibliography: reference.bib
csl: bmc-medicine.csl
language: custom.yml

format:
  pdf:
    documentclass: scrbook
    classoption: ["onepage", "openany"]
    mainfont: "Times New Roman"
    sansfont: "Times New Roman"
    monofont: "Times New Roman"
    template-partials:
      - "before-body.tex"
      - "_titlepage.tex" 
    include-in-header: 
      - "in-header.tex"
    toc: true
    lof: true
    lot: true


        
